name: cameratraps-classifier

channels:
- conda-forge
- pytorch

dependencies:
- python>=3.7
- pytorch::pytorch=1.10.1
- pytorch::torchvision=0.11.2
- conda-forge::cudatoolkit=11.3.1
- conda-forge::cudnn=8.2
- humanfriendly=10.0
- jsonpickle=2.2.0
- matplotlib=3.7.1
- numpy=1.21.5
- pandas=1.3.5
- scikit-learn=1.0.2
- tqdm=4.64.1
- progressbar2=4.2.0
- pip

- pip:
  - azure-storage-blob==12.16.0
  - Pillow==9.3.0
  - setuptools==59.5.0
  - tensorboard==2.11.2

